### ISSUE TITLE
通过modal层获取登录地址靠谱不

### ISSUE THREAD

**Issue by henry-fun** [ohroy/segmentfault_loginer#1]
![2016-06-14_092705](https://cloud.githubusercontent.com/assets/7412531/16028479/472d2b5c-3212-11e6-8b88-5d681dd9b6de.jpg)

点击segnmentfault的登录按钮会跳出一个modal层，我通过观察这个modal层的代码，发现了你在文章中说到的登录地址，这种方法靠谱不？

**Comment by ohroy** [comment]
对于这里来说是可行的，对于大多数情况下也是可行的。  
但是有些情况下，他们可能通过js来修改此处的地址（不太常见）。  

---

通过观察网络面板是最靠谱最稳定最简单的方法。
